sudo: false

language: generic


before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
- export HADDOCK_ROOT="$(stack path --dist-dir)"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $HADDOCK_ROOT/doc/html/studienarbeit-minesweeper
  github_token: $GITHUB_TOKEN # das Token damit der Travis das darf, soll nicht in den Logs stehen, daher Variable
  on:
    branch: master

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
